QDEMO
	;
	S ^MI(":WS","ROUTES","OPTIONS","qdemo","API^QDEMO")=""
	S ^MI(":WS","ROUTES","POST","qdemo","API^QDEMO")=""
	;
	Q
	;
	;
API(%Q,%R,%A)
	N %J
	S %R("mime")="application/json"
	S %R("header","Access-Control-Allow-Origin")="*"
	S %R("header","Access-Control-Allow-Headers")="Origin, X-Requested-With, Content-Type, Accept, auth, jwt"
	I '$D(@%Q("body")) Q
	N %RR D DECODE^MIWS(%Q("body"),"%RR")
	N %ROUTINE S %ROUTINE=%RR("routine")
	K %RR("routine") K %J
	;	
	D @(%ROUTINE_"(.%RR,.%J)")
	K @%R D ENCODE^MIWS("%J",%R)
	Q
	;
	;
EXAMPLE1(I,O)
	S OUTPUT=$NA(O("data","data"))
	F I=1:1:10 S @OUTPUT@(I)=I("data","param")_" HAIDER => "_I
	Q
	;
EXAMPLE2(I,O)
	N FIRSTNAME,LASTNAME
	S ACCOUNT=I("data","account")
	S FIRSTNAME=I("data","firstname")
	S LASTNAME=I("data","lastname")
	S ^DEMO(ACCOUNT)=FIRSTNAME_":"_LASTNAME
	S O("data","result")=$P(^DEMO(ACCOUNT),":",2)
	Q
	;
GETDASHBOARD(I,O)
	N TOTALPATIENT,TOTALDONOR,TOTALUNIT
	S (TOTALPATIENT,TOTALDONOR,TOTALUNIT)=0
	N A S A="" F  S A=$O(^PATIENT(A)) Q:A=""  D 
	. S TOTALPATIENT=TOTALPATIENT+1
	. I $P(^PATIENT(A),":",4)=1 S TOTALDONOR=TOTALDONOR+1
	. S TOTALUNIT=TOTALUNIT+$P(^PATIENT(A),":",5)
	S O("data","patientsTotal")=TOTALPATIENT
	S O("data","donorsTotal")=TOTALDONOR
	S O("data","unitsTotal")=TOTALUNIT
	Q
	;
; DONORLIST(I,O)
; 	;
; 	N DONORS,DONOR1
; 	S DONORS=$NA(O("data","donors"))
; 	S DONORS1=""
; 	N A S A="" F  S A=$O(^DONOR(A)) Q:A=""  D
; 	. S DONOR=^DONOR(A)
; 	. S DONORS1=DONOR_","_DONORS1
; 	S @DONORS=DONORS1
; 	Q
; 	;
DASHBOARDSEARCH(I,O)
	N PATIENTSSN,FIRSTNAME,LASTNAME,NUMUNITS,SSN,ACCOUNTNUMBER,PATIENTSSNVUE
	S PATIENTSSN=I("data","ssn")
	S FIRSTNAME=$NA(O("data","firstName"))
	S LASTNAME=$NA(O("data","lastName"))
	S NUMUNITS=$NA(O("data","numUnits"))
	S PATIENTSSNVUE=$NA(O("data","ssn"))
	S @FIRSTNAME="NOT FOUND",@LASTNAME="NOT FOUND",@NUMUNITS="NOT FOUND",@PATIENTSSNVUE="NOT FOUND"
	I $G(^PATIENTSSNI(PATIENTSSN))]"" D 
	. S ACCOUNTNUMBER=^PATIENTSSNI(PATIENTSSN) D
	.. S @FIRSTNAME=$P(^PATIENT(ACCOUNTNUMBER),":",1)
	.. S @LASTNAME=$P(^PATIENT(ACCOUNTNUMBER),":",2)
	.. S @PATIENTSSNVUE=$P(^PATIENT(ACCOUNTNUMBER),":",3)
	.. S @NUMUNITS=$P(^PATIENT(ACCOUNTNUMBER),":",4) 
	;	
	Q
	;
INSERTDONOR(I,O)
	N DONORSSN,DONORFIRSTNAME,DONORLASTNAME,NUMUNITS
	S DONORSSN=I("data","ssn")
	S DONORFIRSTNAME=I("data","firstName")
	S DONORLASTNAME=I("data","lastName")
	S NUMUNITS=I("data","unitNum")
	S ISDONER=I("data","isDonor")
	S ^DONOR(DONORSSN)=(DONORSSN_":"_DONORFIRSTNAME_":"_DONORLASTNAME_":"_NUMUNITS_":"_ISDONER)
	Q
	;
INSERTMPATIENT
	K ^PATIENT,^PATIENTSSNI
	N I,SSN,FIRSTNAME,LASTNAME,ISDONOR,NUMUNITS
	F I=1:1:1000000 D
	. S NAMES="HAIDER:KHALED:ALI:AHMED:MAHMOUD:OMER:SAEED:AMER" 
	. S ^PATIENT(I)="FIRSTNAME:LASTNAME:SSN:ISDONER:NUMUNITS"
	. ;
	. S FIRSTNAME=$P(NAMES,":",$R(8)+1)
	. S LASTNAME=$P(NAMES,":",$R(8)+1)
	. S SSN=$R(9)_$R(9)_$R(9)_$R(9)_$R(9)_$R(9)_$R(9)_$R(9)_$R(9)_$R(9)_$R(9)
	. S ISDONOR=$R(2)
	. S NUMUNITS=$R(10)+1
	. ;
	. S $P(^PATIENT(I),":",1)=FIRSTNAME
	. S $P(^PATIENT(I),":",2)=LASTNAME
	. S $P(^PATIENT(I),":",3)=SSN
	. S $P(^PATIENT(I),":",4)=ISDONOR
	. S $P(^PATIENT(I),":",5)=NUMUNITS
	. ;
	. I $G(SSN)]"" S ^PATIENTSSNI(SSN)=I
	Q
	;	
INSERTTDONOR
	K ^DONOR,^DONORSSNI
	N I,SSN,FIRSTNAME,LASTNAME,ISDONOR,NUMUNITS
	F I=1:1:100 D
	. S NAMES="HAIDER:KHALED:ALI:AHMED:MAHMOUD:OMER:SAEED:AMER" 
	. S ^DONOR(I)="FIRSTNAME:LASTNAME:SSN:ISDONER:NUMUNITS"
	. ;
	. S FIRSTNAME=$P(NAMES,":",$R(8)+1)
	. S LASTNAME=$P(NAMES,":",$R(8)+1)
	. S SSN=$R(9)_$R(9)_$R(9)_$R(9)_$R(9)_$R(9)_$R(9)_$R(9)_$R(9)_$R(9)_$R(9)
	. S ISDONOR=$R(2)
	. S NUMUNITS=$R(10)+1
	. ;
	. S $P(^DONOR(I),":",1)=FIRSTNAME
	. S $P(^DONOR(I),":",2)=LASTNAME
	. S $P(^DONOR(I),":",3)=SSN
	. S $P(^DONOR(I),":",4)=ISDONOR
	. S $P(^DONOR(I),":",5)=NUMUNITS
	. ;
	. I $G(SSN)]"" S ^DONORSSNI(SSN)=I
	Q	
	;	
	;
GETTOTALDONOR(I,O)
	N TOTALDONOR
	S COUNT=0
	N A S A="" F  S A=$O(^DONOR(A)) Q:A=""  D
	. I $G(^DONOR(A))]"" S COUNT=COUNT+1
	S O("data","donorsTotal")=COUNT
	Q
DONORLIST(I,O)
	N DONORI,DONOR
	S DONORI=I("data","donori")
	S DONOR=$NA(O("data","donors"))
	I $G(^DONOR(DONORI))]"" D  
	. S @DONOR=^DONOR(DONORI)
	Q
	;
TEST
	K ^TEST
	N I
	S I=""
	S ^TEST=""
	F I=1:1:1000 S ^TEST(I,I)=""	
	;	